### ISSUE TITLE
Not a valid NodeCG Bundle

### ISSUE THREAD

**Issue by superaven** [LtSquigs/giantbomb-extralife-nodecg#1]
When attempting to install the bundle using nodecg-cli, the following error occurs:
```
>nodecg install LtSquigs/giantbomb-extralife-nodecg
Fetching giantbomb-extralife-nodecg release list... done!
Installing giantbomb-extralife-nodecg... done!
Error: There doesn't seem to be a valid NodeCG bundle in this folder:
        c:\Nodes\node_modules\nodecg\bundles\giantbomb-extralife-nodecg
```
Issue appears to the absences of [package.json manifest](http://nodecg.com/tutorial-manifest.html) and possibly other missing configuration data.

**Comment by Lange** [comment]
This will be fixed when the nodecg-v1 branch is merged. This bundle was originally written for a much older version of NodeCG, which is why it is structured the way it currently is. We are in the process of porting it to NodeCG v1.
