### ISSUE TITLE
API Errors

### ISSUE THREAD

**Issue by jasonmasters-git** [LtSquigs/giantbomb-extralife-nodecg#21]
Hello, I tried running the nodecg and it all launches but when I input my donation ID I get this scraper error.  I'm not smart enough to fix it.

> 2021-10-21T02:51:42.140Z - error: [giantbomb-extralife-nodecg] Error scraping Extra Life API: Error: Invalid value rejected for replicant "donations" in namespace "giantbomb-extralife-nodecg":
> 	Field "approved.0" has additional properties: "data.approved[n].links"
> 	Field "approved.0" has additional properties: "data.approved[n].recipientName"
> 	Field "approved.0.message" is the wrong type. Value "null" (type: object) was provided, expected type "string"
>  	Field "approved.1" has additional properties: "data.approved[n].links"
> 	Field "approved.1" has additional properties: "data.approved[n].recipientName"
> 	Field "approved.1.message" is the wrong type. Value "null" (type: object) was provided, expected type "string"
>  
>     at Replicant.validate (H:\Extra Life\giantbomb-extralife-2019-Windows_NT\nodecg\lib\replicant\shared.js:295:12)
>     at Object.set (H:\Extra Life\giantbomb-extralife-2019-Windows_NT\nodecg\lib\replicant\shared.js:174:14)
>     at updateDonations (H:\Extra Life\giantbomb-extralife-2019-Windows_NT\nodecg\bundles\giantbomb-extralife-nodecg\dist\src\extension\scraper.js:122:36)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
>

**Comment by LtSquigs** [comment]
This issue should be resolved with the latest release here https://github.com/giantbomb-extralife/giantbomb-extralife-nodecg/releases/tag/2021 (within what I was able to test)
